### ISSUE TITLE
Deployment Failure (Important enough to review)

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/catalog.data.gov#716]
Workflow with Issue: publish & deploy
Job Failed: deploy
Last Commit: c6dc24a7552c69a74de89586577bae7825ce1ccd
Number of times run: 3
Last run by: robert-bryson
Github Action Run: https://github.com/GSA/catalog.data.gov/actions/runs/3858814807

**Comment by robert-bryson** [comment]
Hmm, well the old ['click the button again'](https://github.com/GSA/catalog.data.gov/actions/runs/3858814807/jobs/6578155027) trick didn't work.

Error from the logs: 
```
2023-01-06T14:45:47.31-0800 [APP/PROC/WEB/0] ERR 2023-01-06 22:45:47,314 ERROR [ckanext.datajson.datajson] Parent identifier not found: "VA-VBA-MASTER-2012ABR-001"
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/bin/ckan", line 8, in <module>
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR sys.exit(ckan())
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 829, in __call__
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR return self.main(*args, **kwargs)
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 782, in main
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR rv = self.invoke(ctx)
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR return _process_result(sub_ctx.command.invoke(sub_ctx))
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR return _process_result(sub_ctx.command.invoke(sub_ctx))
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR return ctx.invoke(self.callback, **ctx.params)
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 610, in invoke
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR return callback(*args, **kwargs)
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/cli.py", line 249, in fetch_consumer
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR utils.fetch_consumer()
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/utils.py", line 355, in fetch_consumer
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR fetch_callback(consumer, method, header, body)
   2023-01-06T14:45:47.35-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 497, in fetch_callback
   2023-01-06T14:45:47.36-0800 [APP/PROC/WEB/0] ERR fetch_and_import_stages(harvester, obj)
   2023-01-06T14:45:47.36-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 515, in fetch_and_import_stages
   2023-01-06T14:45:47.36-0800 [APP/PROC/WEB/0] ERR success_import = harvester.import_stage(obj)
   2023-01-06T14:45:47.36-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/ckanext/datajson/datajson.py", line 465, in import_stage
   2023-01-06T14:45:47.36-0800 [APP/PROC/WEB/0] ERR parent = self.is_part_of_to_package_id(parent_identifier, harvest_object)
   2023-01-06T14:45:47.36-0800 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/ckanext/datajson/datajson.py", line 437, in is_part_of_to_package_id
   2023-01-06T14:45:47.36-0800 [APP/PROC/WEB/0] ERR raise ParentNotHarvestedException('Unable to find parent dataset. Raising error to allow re-run later')
   2023-01-06T14:45:47.36-0800 [APP/PROC/WEB/0] ERR ckanext.datajson.exceptions.ParentNotHarvestedException: Unable to find parent dataset. Raising error to allow re-run later
```

**Comment by nickumia-reisys** [comment]
Ohhh that's super interesting!! We haven't seen this happen before.  The error has nothing to do with the PR being merged.  The issue had to have been that there were some items in the queue still and when the app was restarted it hit one of the known bugs and crashed.  It just so happened that the restart was caused by a deployment and not normal restarting processes (either by cloud.gov or our restart action).  I would assume re-running this enough times would get it to "pass" even though the metric of passing is irrelevant in this case.

On a separate note, it seems like there's a bug somewhere.  The name of the app should be shown in the github action titles and also on this ticket.  Some variable isn't being handled properly and that's why it's not showing up.  It would be a lot easier to debug this if the title was named properly (not saying it's this ticket's job to fix it, but it should be pretty easy to track down).

**Comment by nickumia-reisys** [comment]
@FuhuXia Harvesting hasn't shown this level of weakness before.  There are still items left in the fetch queue and it's 6p EST.

**Comment by nickumia-reisys** [comment]
@btylerburton See!  I'm not crazy for wanting these issues.  I don't know if we would have ever noticed that harvesting had this issue without this.  We would have needed to be monitoring the harvesting jobs.  But only @FuhuXia really does that haha..

**Comment by btylerburton** [comment]
For the record, I fully support the creation of these tickets. 😎

**Comment by FuhuXia** [comment]
The `ParentNotHarvestedException` is very common during harvesting. Some harvest source will generate tons of this exception. It never becomes an issue for deployment before. Maybe wait until this harvest source to finish harvesting then retry deployment, or we have to deal with this exception gracefully so that it wont kill the process and fail the heath check.

**Comment by nickumia-reisys** [comment]
The deployment has now passed, but the discovery that we've made is that there's yet another aspect to an issue failing and that is... Harvesting errors! dun dun dunnnnn....

As an incomplete list of things we need to be cognizant of for our CD pipeline,
- Restarts and deployments interrupting each other
- Memory quota issues with apps and tasks running
- Real deployment failures  (like app literally cannot start issues)
- External issues with buildpacks, python libraries, strange network issues
- Harvesting causing app failures

It just seems like there are quite a few flimsy pieces in all of this.  I have no concrete ideas on how to improve it, but just want to emphasis that there is a LOOOTTT going on 😢 

![image](https://user-images.githubusercontent.com/85196563/211166775-4cc5f863-eb96-4348-a0dc-3708243e2901.png)
